[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
encode_tic_tac_toe = "BK7T9pvXgFX1zisDETbrrqqsCfZFmW6KKZ9wihwiMFcw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/samuelfernandez/.config/solana/id.json"
rpc_port = 8900
faucet_port = 8901

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

